### ISSUE TITLE
BUG: Local (installed) database is out of sync with package database

### ISSUE THREAD

**Issue by 1Naim** [CachyOS/chwd#143]
Following #142 and mesa 24.2.7 release. These following packages were made obsolete:

```
libva-mesa-driver
mesa-vdpau
lib32-libva-mesa-driver
lib32-mesa-vdpau
```

The aforementioned PR addresses this. However, existing systems will not be able to reinstall the relevant profiles due to the packages being replaced and no longer installed on the system. Below is the error when trying to reinstall (force install) the AMD profile.

```sh
❯ sudo chwd -i amd -f
> Removing amd ...
WARNING: An unknown hook is being called
WARNING: An unknown hook is being called
error: target not found: libva-mesa-driver
error: target not found: lib32-libva-mesa-driver
error: target not found: mesa-vdpau
error: target not found: lib32-mesa-vdpau
ERROR: Pacman command was failed! Exit code: 1
Error: script failed!
Error: Error occurred
```

**Comment by ventureoo** [comment]
Please check the fix: https://github.com/CachyOS/chwd/pull/144
